name: CI/CD Pipeline Avanzado

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Ejecutar Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Cache de dependencias
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npx vitest run

      - name: Guardar resultados de pruebas
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node }}
          path: coverage/
  build:
    name: Build del Proyecto
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build de aplicación
        run: |
          mkdir build
          echo "Build exitoso - $(date)" > build/info.txt

      - name: Subir artifact de build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/
