name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npx vitest run
