name: Despliegue a Staging

on:
  workflow_run:
    workflows: ["CI/CD Pipeline Avanzado"]
    types:
      - completed

jobs:
  deploy:
    name: Desplegar a GitHub Pages (Staging)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Descargar build
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: public/

      - name: Simular despliegue
        run: |
          echo "Desplegando a entorno de staging..."
          ls -l public
  notify-on-failure:
    name: Notificar en fallo
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    steps:
      - name: Crear issue en caso de error
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "ERROR❌: Fallo en el despliegue de staging",
              body: "Hubo un error en el job de deploy del pipeline `CI/CD Pipeline Avanzado`.\nRevisar el historial de acciones para más detalles: https://github.com/${context.repo.owner}/${context.repo.repo}/actions"
            });
